/*

AUTOGENERATED KERNEL
Settings:
 LMUL=1
 M=2
 M_tail_scalar_from=2
 N=2
 __riscv_='__riscv_'
 complex=False
 conjugate=False
 cpu='zvl256b'
 force_acc_double=False
 index_type='BLASLONG'
 op='trmm'
 param_precision='float'
 reg_width_bits=256
 tail_policy=''
 trace=False

Derived:
 ELEN_ACC=32
 ELEN_PARAM=32
 LMUL_ACC=1
 VFMACC='__riscv_vfmacc_vf_f32m1'
 VFMUL='__riscv_vfmul_vf_f32m1'
 VLEV='__riscv_vle32_v_f32m1'
 VLSEV='__riscv_vlse32_v_f32m1'
 VMACC_TO_ACC='__riscv_vfmacc_vf_f32m1'
 VMUL_TO_ACC='__riscv_vfmul_vf_f32m1'
 VSETVL='__riscv_vsetvl_e32m1'
 VSEV='__riscv_vse32_v_f32m1'
 VSSEV='__riscv_vsse32_v_f32m1'
 acc_vector_t='vfloat32m1_t'
 output='strmm_kernel_2x2_zvl256b.c'
 param_scalar_t='float'
 param_vector_t='vfloat32m1_t'

*/

#include "common.h"



#if defined(LEFT) != defined(TRANSA)
    #define BACKWARDS
#endif

int CNAME(BLASLONG M, BLASLONG N, BLASLONG K, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc, BLASLONG offset)

{
    BLASLONG gvl = 0;
    BLASLONG m_top = 0;
    BLASLONG n_top = 0;


    // -- MAIN PASS

    for (BLASLONG j=0; j<N/2; j+=1) {
        m_top = 0;
        BLASLONG gvl = __riscv_vsetvl_e32m1(2);


        for (BLASLONG i=0; i<M/2; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            BLASLONG pass_K = K;
            #ifdef LEFT
                BLASLONG off = offset + m_top;
            #else
                BLASLONG off = -offset + n_top;
            #endif
            #ifdef BACKWARDS
                ai += off*2;
                bi += off*2;
                pass_K -= off;
            #else
                #ifdef LEFT
                    pass_K = off + 2;
                #else
                    pass_K = off + 2;
                #endif
            #endif
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            bi += 2;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 2;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);

            for(BLASLONG k=1; k<pass_K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 2;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vfmul_vf_f32m1( result0, alpha, gvl );
            vfloat32m1_t c1 = __riscv_vfmul_vf_f32m1( result1, alpha, gvl );
            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl);
            m_top += 2;
        }



        // -- tails for main pass

        if( M & 1 ) {
            float result0 = 0;
            float result1 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            BLASLONG pass_K = K;
            #ifdef LEFT
                BLASLONG off = offset + m_top;
            #else
                BLASLONG off = -offset + n_top;
            #endif
            #ifdef BACKWARDS
                ai += off*1;
                bi += off*2;
                pass_K -= off;
            #else
                #ifdef LEFT
                    pass_K = off + 1;
                #else
                    pass_K = off + 2;
                #endif
            #endif

            for(BLASLONG k=0; k<pass_K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+0]*B[bi+1];
                ai+=1;
                bi+=2;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] = alpha * result0;
            C[ci+1*ldc+0] = alpha * result1;
            m_top+=1;
        }

        n_top += 2;
    }



    // -- tails for N=1

    if( N & 1 ) {
        gvl = __riscv_vsetvl_e32m1(2);
        m_top = 0;

        for (BLASLONG i=0; i<M/2; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            BLASLONG pass_K = K;
            #ifdef LEFT
                BLASLONG off = offset + m_top;
            #else
                BLASLONG off = -offset + n_top;
            #endif
            #ifdef BACKWARDS
                ai += off*2;
                bi += off*1;
                pass_K -= off;
            #else
                #ifdef LEFT
                    pass_K = off + 2;
                #else
                    pass_K = off + 1;
                #endif
            #endif
            float B0 = B[bi+0];
            bi += 1;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 2;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);

            for(BLASLONG k=1; k<pass_K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 2;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vfmul_vf_f32m1( result0, alpha, gvl );
            __riscv_vse32_v_f32m1( &C[ci], c0, gvl);
            m_top += 2;
        }


        if( M & 1 ) {
            float result0 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            BLASLONG pass_K = K;
            #ifdef LEFT
                BLASLONG off = offset + m_top;
            #else
                BLASLONG off = -offset + n_top;
            #endif
            #ifdef BACKWARDS
                ai += off*1;
                bi += off*1;
                pass_K -= off;
            #else
                #ifdef LEFT
                    pass_K = off + 1;
                #else
                    pass_K = off + 1;
                #endif
            #endif

            for(BLASLONG k=0; k<pass_K; k++) {
                result0+=A[ai+0]*B[bi+0];
                ai+=1;
                bi+=1;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] = alpha * result0;
            m_top+=1;
        }

        n_top += 1;
    }

    return 0;
}

